In [7]:
from scipy.io import loadmat
import numpy as np

mat_path = "/Users/yuhanglan/Desktop/大学/博士/PINN/PII/pde_discovery/data/KdV-PINN.mat"
out_path = "KdV-PINN.npy"

mat = loadmat(mat_path)

x = mat["x"].ravel()
t = mat["t"].ravel()
usol = mat["usol"]

# usol shape is (len(x), len(t)), so transpose it to match meshgrid(x, t)
X, T = np.meshgrid(x, t, indexing="xy")

data = np.column_stack([
    X.ravel(),
    T.ravel(),
    usol.T.ravel(),
])

np.save(out_path, data)

print(f"Saved: {out_path}")
print(f"data shape: {data.shape}")
print(data[:5])

Saved: KdV-PINN.npy
data shape: (102912, 3)
[[-1.          0.         -1.        ]
 [-0.99609375  0.         -0.9999247 ]
 [-0.9921875   0.         -0.99969882]
 [-0.98828125  0.         -0.99932238]
 [-0.984375    0.         -0.99879546]]
